# Generated by Django 6.0.3 on 2026-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('original_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.IntegerField(default=0)),
            ],
        ),
    ]
